version: '2'

services:
  dev:
    image: talend-codegen-build
    build:
      context: .
      args:
        BUILDER_UID: 1000
    environment:
      - PATH=/app/bin:/home/builder/.local/bin:$PATH
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - './:/app'
  app:
    image: tos:7.3.1
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - DISPLAY
    stdin_open: true
    tty: true
    volumes:
      - './:/app'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    entrypoint: /opt/TOS_DI-20200219_1130-V7.3.1/talend.sh
